### ISSUE TITLE
[2024.11.26] TILs 🩷

### ISSUE THREAD

**Issue by funcsom** [funcsom/goorm_coding_section#5]
# Link
https://funcsom.github.io/goorm_coding_section/kiosk_1126/kiosk.html

# TILs
### To-Do-Lists
- [x] 강사님의 kioskEasy.js 파일 분석하기
- [ ] kiosk.js 파일에서 버튼 클릭시마다 cartDisplay 요소가 초기화되는 로직을 사용해서, 이를 최적화하고자, 기존의 DOM 요소에 글씨를 추가하는 로직을 짜볼 것이다.. (되려나)
- [x] 카테고리 탭을 통해 메뉴를 선택적으로 렌더링하기
- [x] JS에서 DOM을 다루는 내장함수를 더 알아볼 것

### 오늘의 학습은 어땠나요?
- 야매로 배워서 js를 통해 DOM을 제어하는 코드는 건너뛰었더니.. 세상에... 모르는 내장함수가 너무 많았다... (여태까지의 나는 React를 위한 JS만 한 느낌이었는데, 찐 JS를 파니 모르는 것 투성이이다)
- 다행히도 코드를 보는 방법을 알아 강사님이 주신 코드와 gpt가 제공해준 코드를 이해할 수 있었다.
- 첫 번째로 하고자 했던 것은, cart 화면에 요소가 추가되면 해당 요소의 왼쪽, 오른쪽에 + 버튼, - 버튼 그리고 delete 버튼을 렌더링 하는 것이었는데, 이를 구현해내기 위해서 강사님이 제공해주신 코드를 분석해본 짬바 (고작 몇시간만의..) 토대로 addEventListener를 사용해서 구현해보았다.
-> 하지만,,, 콜백 함수의 지옥마냥 이벤트 핸들러 함수 안에 또 이벤트 핸들러 함수를 집어넣은 하드코딩을 하였고, 이때 cart 객체는 제어가 되는 것이 분명했으나, updateCart 함수의 렌더링 시점을 직접 지정하지 못했다. (다른 메뉴를 클릭해 cart 객체에 다른 메뉴를 추가하는 시점에 이전에 눌렀던 메뉴의 결과가 렌더링되었다.)
-> 결국은 GPT에게 도움을 청했고, 해당 버튼에 대한 핸들러를 바깥으로 빼는 모듈화를 진행하였다. 해당 버튼의 class를 classList를 add를 통해 지정하고, dataset을 통해 함께 전달할 데이터를 저장했다. 그리고 버튼의 부모 요소인 cartDisplay를 addEventListener() 처리하여 cart를 업데이트할 수 있도록 로직을 수정했다. (이곳에서, classList.contains()을 통해 해당 클래스를 식별하고, dataset을 통해 저장한 데이터를 가져오는 로직이었다.)
- 다음으로 구현해보고자 한 것은, 카테고리 탭을 분류하여 선택적 DOM 렌더링을 진행하고자 했다. 이때도 핸들러 함수 안의 핸들러인 하드코딩을 진행했는데, 그 이유는 위의 "classList와 dataset에 관련한 깨달음"을 몰랐기 때문이다. issue를 적으면서 비로소 깨달음... 그냥 와랄라 "시간안에 해내고싶어~" 라는 마음에 뇌빼고 코딩했던 느낌... (코드를 작성할때까지만 해도 나는, 데이터값들을 DOM 요소 사이로 어떻게 넘겨받는지의 로직을 전혀 이해하지 못했음)
- 오늘은 지피티에게 코드를 제공하고 해당 코드의 로직을 확인하고 내가 다시 코딩해보는 과정의 연속이었다. 
-> 카테고리를 분류하는 데에 3시간이 조금 넘게 걸렸다. 아무래도 기초가 부족한 탓도 있고, DB에서 데이터를 어떻게 불러오는 것이 좋을까? 에 관련된 것을 조금이라도 고려해보고 설정한 로직이기 때문이다.... (html에서는 카테고리만 생성해놓고, DB에서 {카테고리, 메뉴명, 가격} 형태의 객체로 묶인 배열을 받아서, 선택적 렌더링을 하면 메뉴가 추가되었을 때 유지보수 측면에서 유리할 것이라고 생각했음...

### 오늘 배운 내장함수 및 무언가를 정리하자
- .querySelector()
- .addEventListener()
- .getAttribute()
- .createElement()
- .innerHTML()
- classList.add()
- classList.contain()
- dataset.어쩌고 = 변수

- [ ] 주석도 내일 쓸 것...
- [ ] classList와 dataSet에 대해서 자세히 알아볼 것...

**Comment by funcsom** [comment]
### js에서 HTML 요소들을 제어하는 방법

1. document.createElement()로 생성 -> 기존 요소에 appendChild()로 추가
2. innerHTML을 사용하여 기존 요소에 자식 요소 추가
3. insertAdjacentHTML()을 사용하여 기존 요소에 대해 HTML을 특정 위치에 삽입
4. append(), prepend() 메서드를 사용하여 텍스트와 요소를 혼합하여 추가 (알고보니 그냥 요소 하나만 추가도 가능하다!)
5. document.createDocumentFragment()로 여러 요소를 한번에 받아서 추가
6. templete을 이용해 복잡한 HTML 구조를 효율적으로 복제 (이것은 웬만하면 필요 없을듯..)

-> +, - 버튼을 만드려고, 가상 노드인 DocumentFragment를 생성한 다음 insertAdjacentHTML()을 사용하려고 했지만, DocumentFragment는 DOM 트리에 직접 포함되지 않는 임시 객체이므로 해당 메서드를 사용할 수 없다고 한다.
-> 그냥 item에 포함시키면 되잖아?? 였다.
```
for (const name in cart) {
    const { price, count } = cart[name];
    total += price * count;
    const item = document.createElement("div"); // html을 js로 제어하겠다
    item.textContent = `${name} x ${count} (${(
      price * count
    ).toLocaleString()}원)`;
    item.insertAdjacentHTML("afterbegin", "<button>-</button>");
    item.insertAdjacentHTML("beforeend", "<button>+</button>");

    cartDisplay.appendChild(item); // 이거 이해 안됨
  }
```
-> 이렇게 했더니, 각각의 버튼 요소들을 제어하기 쉽지 않았다. 그래서 결국 버튼을 추가해서 했다ㅜㅜ

-> append(), prepend() 했다…
```
아몰랑
```

-> classList와 contain을 통해 이를 제어하기
-> dataset도 잘 모르겠다.

- 렌더링 시점 또한 생각해봐야해서. 확실히 어렵다…

- 내일 할랭 졸려
https://realzzu.tistory.com/107 <- 자꾸 push 오류날 때 쓰기 왜인진 나도 모름 내일의 나에게

**Comment by RunaUXLabs** [comment]
회고가 아주 재밌습니다 ㅎㅎㅎ
5번은 새로운 시도인데 돌아왔군요😹
6번 같은 경우엔 클래스객체로 찍어내는 형태의 대규모 플젝에서는 사용되죠.
(간단키오스크에서는 그렇게 까진 필요 없으니깐)

탭을 구현하는데 데이터 기반으로 필터함수 써서 생성 후 렌더링 하도록 했네요.
퍼블용 딸깍이는 미리 다 만들어 놓고 보여주는것만 다르게 보여주는 식이잖아요. 정적.

데이터 기반으로 생성하라고 하는게 실시간 업데이트가 되니까 오히려 유지보수엔 이게 나을지도요.
만약 다 만들어진걸 보여주는 식이라면,
해당 메뉴가 단종되면 DB도 업데이트 하고 화면도 고쳐야하지만
데이터 기반이면 DB만 업데이트하면 화면은 자동이니까요!

이런저런 재미있는 생각 확장 보기 좋아요!

**Comment by KwanLee1129** [comment]
멋쥐다... 코딩대장.... 
단계별로 정리된 회고 좋네요 👍
